#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/UnitInfo/UnitInfo.cshtml")]
    public partial class _Mobile_Views_UnitInfo_UnitInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_UnitInfo_UnitInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
  
    var platId = Request["r"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 149), Tuple.Create("\"", 213)
            
            #line 8 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
, Tuple.Create(Tuple.Create("", 156), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 156), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 287), Tuple.Create("\"", 344)
            
            #line 9 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
, Tuple.Create(Tuple.Create("", 294), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 294), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 418), Tuple.Create("\"", 455)
            
            #line 10 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
, Tuple.Create(Tuple.Create("", 425), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/Unit.css")
            
            #line default
            #line hidden
, 425), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(" />\r\n    <!--Import jQuery before materialize.js-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 745), Tuple.Create("\"", 792)
            
            #line 14 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
, Tuple.Create(Tuple.Create("", 751), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 751), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 839), Tuple.Create("\"", 896)
            
            #line 15 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
, Tuple.Create(Tuple.Create("", 845), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 845), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 943), Tuple.Create("\"", 988)
            
            #line 16 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
, Tuple.Create(Tuple.Create("", 949), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 949), false)
);

WriteLiteral("></script>\r\n\r\n    <title>CarrierWechat</title> \r\n</head>\r\n<body>\r\n    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            保固查询\r\n                        </a>\r\n              " +
"      </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n       " +
" <!-- end header nav-->\r\n    </header>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(" id=\"form1\"");

WriteLiteral(" name=\"form1\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" id=\"tips\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                凭机组序列号查询\r\n                    " +
"                        </div>\r\n                                            <spa" +
"n");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"UnitNumber\"");

WriteLiteral(" id=\"UnitNumber\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" placeholder=\"请输入机组序列号\"");

WriteLiteral(" onkeyup=\"value=value.replace(/[\\\']+/, \'\') \"");

WriteLiteral(">\r\n                                                <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnQuery\"");

WriteLiteral(">确定</button>\r\n                                                <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnReset\"");

WriteLiteral(@">重置</button>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script>
    $(function () {
        //搜索
        ");

WriteLiteral("\r\n        //搜索\r\n        $(\"#btnQuery\").click(function () {\r\n            var unitN" +
"umber = $.trim($(\"#UnitNumber\").val());\r\n            if (unitNumber != \"\") {\r\n  " +
"              $.post(\"");

            
            #line 96 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
                   Write(Url.Action("GetUnitInformationList", "UnitInfo"));

            
            #line default
            #line hidden
            
            #line 96 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
                                                                    Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@""", { UnitNumber: unitNumber }, function (data) {
                    if (!data.IsSuccess) {
                        alert(""您查找机组不存在"");
                        //return false;
                    }
                    else {
                        var checkresult = """);

            
            #line 102 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
                                      Write(Url.Action("UnitCheckResult", "UnitInfo"));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Mobile\Views\UnitInfo\UnitInfo.cshtml"
                                                                                Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&UnitNumber="" + data.ExtInfo.UnitNumber;
                        location.href = checkresult;//实现页面的跳转
                    }
                })
            }
            else {
                $(""#UnitNumber"").val("""");
            }
        });
        //重置
        $(""#btnReset"").click(function () {
            $(""#UnitNumber"").val("""");
        })
    });
</script>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
