#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/UnitInfo/UnitCheckResult.cshtml")]
    public partial class _Mobile_Views_UnitInfo_UnitCheckResult_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_UnitInfo_UnitCheckResult_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
  
    var platId = Request["r"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 149), Tuple.Create("\"", 213)
            
            #line 8 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 156), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 156), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 287), Tuple.Create("\"", 344)
            
            #line 9 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 294), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 294), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 418), Tuple.Create("\"", 460)
            
            #line 10 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 425), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/UnitCheck.css")
            
            #line default
            #line hidden
, 425), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(">\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(" />\r\n    <!--Import jQuery before materialize.js-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 748), Tuple.Create("\"", 795)
            
            #line 14 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 754), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 754), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 842), Tuple.Create("\"", 899)
            
            #line 15 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 848), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 848), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 946), Tuple.Create("\"", 991)
            
            #line 16 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 952), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 952), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1038), Tuple.Create("\"", 1080)
            
            #line 17 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 1044), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/Jquery.Query.js")
            
            #line default
            #line hidden
, 1044), false)
);

WriteLiteral("></script>\r\n    <title>CarrierWechat</title>        \r\n</head>\r\n<body>\r\n    <heade" +
"r");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            保固查询\r\n                        </a>\r\n              " +
"      </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n       " +
" <!-- end header nav-->\r\n    </header>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <form");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" for=\"UnitType\"");

WriteLiteral(" class=\"UnitType\"");

WriteLiteral(">机组型号</label>\r\n                                            </br>\r\n               " +
"                             <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"UnitType\"");

WriteLiteral(" id=\"UnitType\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(">\r\n                                            </br>\r\n                           " +
"                 </br>\r\n\r\n                                            <label");

WriteLiteral(" for=\"DeadLine\"");

WriteLiteral(" class=\"DeadLine\"");

WriteLiteral(">保修期限</label>\r\n                                            </br>\r\n               " +
"                             <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"DeadLine\"");

WriteLiteral(" id=\"DeadLine\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(">\r\n                                            </br>\r\n                           " +
"                 </br>                                          \r\n              " +
"                              <div");

WriteLiteral(" id=\"comment\"");

WriteLiteral(">如需查询详细内容，请联系021-111111</div>                                           \r\n       " +
"                                     </br>\r\n                                    " +
"        </br>\r\n\r\n                                            <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnBack\"");

WriteLiteral(@">返回</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script>
        $(function () {
            init();
            $(""#btnBack"").click(function () {
                var back = """);

            
            #line 77 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
                       Write(Url.Action("UnitInfo", "UnitInfo"));

            
            #line default
            #line hidden
            
            #line 77 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
                                                          Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@""";
                location.href = back;
                return false;//表单里的<button>标签定义的按钮会自动提交，返回false阻止其提交
            })
        })
        //初始化页面元素
        function init() {
            var UnitNumber = $.query.get(""UnitNumber"");
            $.ajax({
                url: """);

            
            #line 86 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
                 Write(Url.Action("GetUnitInformationList", "UnitInfo"));

            
            #line default
            #line hidden
            
            #line 86 "..\..\Mobile\Views\UnitInfo\UnitCheckResult.cshtml"
                                                                  Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&UnitNumber="" + UnitNumber,
                data: {},
                success: function (data) {
                    if (data != null) {
                        $(""#UnitType"").val(data.ExtInfo.UnitType);
                        $(""#DeadLine"").val(data.ExtInfo.DeadLine.replace(""T"","" ""));
                    }
                }

            });
        }
    </script>

</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
