#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/PartInfo/CheckResult.cshtml")]
    public partial class _Mobile_Views_PartInfo_CheckResult_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_PartInfo_CheckResult_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
  
    //var code = Request["code"];
    //var id = Request["id"];
    var platId = Request["r"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 215), Tuple.Create("\"", 279)
            
            #line 10 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 222), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 222), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 353), Tuple.Create("\"", 410)
            
            #line 11 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 360), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 360), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(" />\r\n    <!--Import jQuery before materialize.js-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 700), Tuple.Create("\"", 747)
            
            #line 15 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 706), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 706), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 794), Tuple.Create("\"", 851)
            
            #line 16 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 800), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 800), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 898), Tuple.Create("\"", 943)
            
            #line 17 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 904), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 904), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 990), Tuple.Create("\"", 1032)
            
            #line 18 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
, Tuple.Create(Tuple.Create("", 996), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/Jquery.Query.js")
            
            #line default
            #line hidden
, 996), false)
);

WriteLiteral(@"></script>
    <title>CarrierWechat</title>
    <style>
        .error {
            font-size: 12px;
            color: rgb(255, 0, 0);
            margin-top: -16px;
        }
        body {
            height:100%;
        }
    </style>
</head>
<body>
    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            零件价格查询\r\n                        </a>\r\n            " +
"        </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n     " +
"   <!-- end header nav-->\r\n    </header>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">                                                                          \r\n    " +
"                                 <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                          <form");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(">                                                                                " +
"          \r\n                                              <label");

WriteLiteral(" for=\"PartNumber\"");

WriteLiteral(" style=\"position:absolute;top:20%;left:16%;width:50%;height:5%;color:#000;font-si" +
"ze:1.2em\"");

WriteLiteral(">零件</label>\r\n                                                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"PartNumber\"");

WriteLiteral(" id=\"PartNumber\"");

WriteLiteral("  value=\"\"");

WriteLiteral(" style=\"position:absolute;top:20%;left:34%;width:50%;height:30px;border:2px solid" +
" gray;color:#000;text-align:center;\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(">\r\n                                                 </br>\r\n                      " +
"                           </br>\r\n\r\n                                            " +
"  <label");

WriteLiteral(" for=\"PartName\"");

WriteLiteral(" style=\"position:absolute;top:30%;left:8%;width:50%;height:5%;color:#000;font-siz" +
"e:1.2em\"");

WriteLiteral(">零件名称</label>\r\n                                                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"PartName\"");

WriteLiteral(" id=\"PartName\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"position:absolute;top:30%;left:34%;width:50%;height:30px;border:2px solid" +
" gray;color:#000;text-align:center\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(">\r\n                                                 </br>\r\n                      " +
"                           </br>\r\n\r\n                                            " +
"  <label");

WriteLiteral(" for=\"Price\"");

WriteLiteral(" style=\"position:absolute;top:40%;left:1%;width:50%;height:5%;color:#000;font-siz" +
"e:1.2em\"");

WriteLiteral(">建议含税零售</label>\r\n                                                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Price\"");

WriteLiteral(" id=\"Price\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"position:absolute;top:40%;left:34%;width:50%;height:30px;border:2px solid" +
" gray;color:#000;text-align:center\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(">\r\n                                                 </br>\r\n                      " +
"                           </br>\r\n                                              " +
"<label");

WriteLiteral(" for=\"Comment\"");

WriteLiteral(" style=\"position:absolute;top:50%;left:28%;width:10%;height:5%;color:#000;font-si" +
"ze:1.2em\"");

WriteLiteral(">注：</label>\r\n                                              <div");

WriteLiteral(" style=\"position:absolute;top:50%;left:34%;width:50%;height:10%;color:#000\"");

WriteLiteral(">此零售价仅指该零件材料费用，不涉及机组维修人工费、上门服务费等其它费用。</div>\r\n                                    " +
"          ");

WriteLiteral("\r\n                                                 </br>\r\n                       " +
"                          </br>\r\n\r\n                                             " +
"    <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnBack\"");

WriteLiteral(" style=\"position:absolute;top:75%;left:40%;width:21%;height:5%;\"");

WriteLiteral(@">返回</button>                                               
                                         </form>
                                     </div>                                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script>
        $(function () {
            init();
            $(""#btnBack"").click(function () {
                var back = """);

            
            #line 94 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
                       Write(Url.Action("PartInfo", "PartInfo"));

            
            #line default
            #line hidden
            
            #line 94 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
                                                          Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@""";
                location.href = back;
                return false;//表单里的<button>标签定义的按钮会自动提交，返回false阻止其提交
            })
        })
        //初始化页面元素
        function init() {
            var partNumber = $.query.get(""PartNumber"");
            $.ajax({
                url: """);

            
            #line 103 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
                 Write(Url.Action("GetPartInformationList", "PartInfo"));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Mobile\Views\PartInfo\CheckResult.cshtml"
                                                                  Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&partNumber="" + partNumber,
                data: {},
                success: function (data) {
                    if (data != null) {
                        $(""#PartNumber"").val(data.ExtInfo.PartNumber);
                        $(""#PartName"").val(data.ExtInfo.PartName);
                        $(""#Price"").val(data.ExtInfo.Price + ""元"");
                    }
                }

            });
        }
</script>
   
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
