#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/PartInfo/PartInfo.cshtml")]
    public partial class _Mobile_Views_PartInfo_PartInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_PartInfo_PartInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
  
    var platId = Request["r"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" style=\"font-size: 16px; width: 100%; height: 100%; overflow: hidden;\"");

WriteLiteral(">\r\n<head>\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 219), Tuple.Create("\"", 283)
            
            #line 8 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 226), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 226), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 357), Tuple.Create("\"", 414)
            
            #line 9 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 364), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 364), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 488), Tuple.Create("\"", 525)
            
            #line 10 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 495), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/Part.css")
            
            #line default
            #line hidden
, 495), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(" />\r\n    <!--Import jQuery before materialize.js-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 815), Tuple.Create("\"", 862)
            
            #line 14 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 821), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 821), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 909), Tuple.Create("\"", 966)
            
            #line 15 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 915), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 915), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1013), Tuple.Create("\"", 1058)
            
            #line 16 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1019), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 1019), false)
);

WriteLiteral("></script>\r\n    <title>CarrierWechat</title>    \r\n</head>\r\n<body>  \r\n    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            零件价格查询\r\n                        </a>\r\n            " +
"        </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n     " +
"   <!-- end header nav-->\r\n</header>  \r\n    <div");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(" id=\"form1\"");

WriteLiteral(" style=\"height:64%;\"");

WriteLiteral(">                                                                                " +
"         \r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"PartTips\"");

WriteLiteral(">\r\n            请输入您需要查询的零件号\r\n        </div>                                      " +
"          \r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"PartNumber\"");

WriteLiteral(" id=\"PartNumber\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" placeholder=\"请输入零件号\"");

WriteLiteral(" onkeyup=\"value=value.replace(/[\\\']+/, \'\') \"");

WriteLiteral(">        \r\n    </div> \r\n    <div");

WriteLiteral(" id=\"btns\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnQueryPart\"");

WriteLiteral(">查询</button>\r\n        <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnResetPart\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">重置</button>\r\n    </div>                              \r\n                         " +
"      \r\n    <script>\r\n    $(function () {\r\n        //搜索\r\n        ");

WriteLiteral("\r\n        //搜索\r\n        $(\"#btnQuery\").click(function () {\r\n            var partN" +
"umber = $.trim($(\"#PartNumber\").val());\r\n            if (partNumber != \"\") {\r\n  " +
"              $.post(\"");

            
            #line 76 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                   Write(Url.Action("GetPartInformationList", "PartInfo"));

            
            #line default
            #line hidden
            
            #line 76 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                                                                    Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\", { partNumber: partNumber }, function (data) {\r\n                    if (!data.I" +
"sSuccess) {\r\n                        alert(\"您查找的零件号不存在\");\r\n                    }" +
"\r\n                    else {\r\n                        var checkresult = \"");

            
            #line 81 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                                      Write(Url.Action("CheckResult", "PartInfo"));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                                                                            Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&PartNumber="" + data.ExtInfo.PartNumber;
                        location.href = checkresult;//实现页面的跳转
                    }
                })
            } else {
                $(""#PartNumber"").val("""");
            }
        })
        //重置
        $(""#btnResetPart"").click(function () {
            $(""#PartNumber"").val("""");
        })
    });
    </script>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
