#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/PartInfo/PartInfo.cshtml")]
    public partial class _Mobile_Views_PartInfo_PartInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_PartInfo_PartInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
  
    //var code = Request["code"];
    //var id = Request["id"];
    var platId = Request["r"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 215), Tuple.Create("\"", 279)
            
            #line 10 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 222), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 222), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 353), Tuple.Create("\"", 410)
            
            #line 11 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 360), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 360), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(" />\r\n    <!--Import jQuery before materialize.js-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 700), Tuple.Create("\"", 747)
            
            #line 15 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 706), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 706), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 794), Tuple.Create("\"", 851)
            
            #line 16 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 800), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 800), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 898), Tuple.Create("\"", 943)
            
            #line 17 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
, Tuple.Create(Tuple.Create("", 904), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 904), false)
);

WriteLiteral(@"></script>

    <title>CarrierWechat</title>
    <style>
        .error {
            font-size: 12px;
            color: rgb(255, 0, 0);
            margin-top: -16px;
        }
        body {
            height:100%
        }
       #PartNumber:focus {
            border-bottom: 0px solid transparent;
            box-shadow: 0 0px 0 0 #26a69a;
        }
    </style>
</head>
<body>  
    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            零件价格查询\r\n                        </a>\r\n            " +
"        </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n     " +
"   <!-- end header nav-->\r\n    </header>  \r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">\r\n                                       ");

WriteLiteral("                                      \r\n                                        <" +
"div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(" id=\"form1\"");

WriteLiteral(" name=\"form1\"");

WriteLiteral(">                                                                                " +
"         \r\n                                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"border:2px solid gray;position:absolute;top:26%;left: 19%;width: 68%;heig" +
"ht: 11%;font-size: 141%;text-align:center;line-height: 4em;\"");

WriteLiteral(">\r\n                                                    请输入您需要查询的零件号\r\n            " +
"                                    </div>\r\n                                    " +
"            <span");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"PartNumber\"");

WriteLiteral(" id=\"PartNumber\"");

WriteLiteral(" ");

WriteLiteral(" value=\"\" style=\"border:1px solid gray;color: gray;position:absolute;top: 42%;lef" +
"t: 17%;width: 66%;height: 5%;border-radius:7px\" placeholder=\"请输入零件号\" onkeyup=\"va" +
"lue=value.replace(/[\\\']+/, \'\') \">\r\n                                             " +
"       <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnQuery\"");

WriteLiteral(" style=\"position:absolute;top: 70%;left:20%;width: 21%;height: 5%;border-radius:6" +
"px\"");

WriteLiteral(">查询</button>\r\n                                                    <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnReset\"");

WriteLiteral(" style=\"position:absolute;top: 70%;left:61%;width: 21%;height: 5%;border-radius:6" +
"px\"");

WriteLiteral(@">重置</button>
                                                </span>                                              
                                            </div>
                                        </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script>
    $(function () {
        //搜索
        $(""#btnQuery"").click(function () {
            var entity = new Object();
            entity.PartNumber = $(""#PartNumber"").val();
            var searchJson = JSON.stringify(entity);
            if (entity.PartNumber != """") {
                $.ajax({
                    url: """);

            
            #line 91 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                     Write(Url.Action("GetPartInformationList", "PartInfo"));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                                                                      Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&partNumber="" + entity.PartNumber,
                    data: {},
                    success: function (data) {
                        if (!data.IsSuccess) {
                            alert(""您查找的零件号不存在"");
                            //return false;
                        }
                        else {
                            var checkresult = """);

            
            #line 99 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                                          Write(Url.Action("CheckResult", "PartInfo"));

            
            #line default
            #line hidden
            
            #line 99 "..\..\Mobile\Views\PartInfo\PartInfo.cshtml"
                                                                                Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&PartNumber="" + data.ExtInfo.PartNumber;
                            location.href = checkresult;//实现页面的跳转
                        }
                    }
                });
            }
            else
                return false;
        })
        $(""#btnReset"").click(function () {
            $(""#PartNumber"").val("""");
        })
    });
    </script>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
