#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/RepositoryArticle/MobileRepositoryArticleDetail.cshtml")]
    public partial class _Mobile_Views_RepositoryArticle_MobileRepositoryArticleDetail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_RepositoryArticle_MobileRepositoryArticleDetail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Mobile\Views\RepositoryArticle\MobileRepositoryArticleDetail.cshtml"
  
    Layout = "~/mobile/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "产品知识库";
    var aid = Request["aid"];

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    .form_detail_row {
        color: rgb(103, 98, 98);
    }
    .articleImage {
        width: 100%;
    }
    .articleTitle {
        font-size: 1.4em;
        color: black;
    }
    .articleInfo {
        word-wrap: break-word;
    }
        .articleInfo img {
        max-width:100%;
        }
</style>
<div");

WriteLiteral(" class=\"lshm_container no_bottomfixed\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"lshm_form\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"form1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form_content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form_detail\"");

WriteLiteral(" style=\"padding: 12px 15px 0 15px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form_detail_row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"articleTitle\"");

WriteLiteral("></div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form_detail_row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"margin-top:-14px;\"");

WriteLiteral(" class=\"articleDate\"");

WriteLiteral("></div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form_detail_row\"");

WriteLiteral(" style=\"margin-bottom:0\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"articleImage\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form_detail_row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"articleInfo\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </form>\r\n    </div>\r\n</div>\r\n<script>\r\n    $(function () {\r\n        $(fu" +
"nction () {\r\n            $.post(\"");

            
            #line 50 "..\..\Mobile\Views\RepositoryArticle\MobileRepositoryArticleDetail.cshtml"
               Write(Url.Action("GetRepositoryArticleEntityById", "RepositoryArticle"));

            
            #line default
            #line hidden
            
            #line 50 "..\..\Mobile\Views\RepositoryArticle\MobileRepositoryArticleDetail.cshtml"
                                                                                 Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\", { id: \'");

            
            #line 50 "..\..\Mobile\Views\RepositoryArticle\MobileRepositoryArticleDetail.cshtml"
                                                                                                                          Write(aid);

            
            #line default
            #line hidden
WriteLiteral(@"' }, function (data) {
                if (data.ExtInfo != null) {
                    $("".articleTitle"").html(data.ExtInfo.Title);
                    $("".articleDate"").html(data.ExtInfo.UploadTime.split(""T"")[0] + ""&nbsp;&nbsp;"" + ""阅读量："" + data.ExtInfo.Quantity);
                    $("".articleImage"").attr(""src"", data.ExtInfo.CoverImgUrl);
                    $("".articleInfo"").html(data.ExtInfo.Contents);
                }
            });
        })
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
