#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Part\EditPartInfo.cshtml"
    using Qxun.UI.Background.App_Code;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Part\EditPartInfo.cshtml"
    using Qxun.UI.Background.Config;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Part/EditPartInfo.cshtml")]
    public partial class _Views_Part_EditPartInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Part_EditPartInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Part\EditPartInfo.cshtml"
   ViewBag.Title = "编辑零件信息";
 ViewBag.subTitle = "零件信息管理";
 Layout = "~/Views/Shared/_Layout.cshtml";
 //如果要上传原尺寸图像，请将本参数赋值为"panorama"
 ViewData["panorama"] = "panorama";
 var platid = Request["plat"];
 var formTitle = "编辑零件信息";
 string content = "", value = "";

 ViewBag.formlines = new FormLineConfig[] {
       new FormLineConfig(){desc = "零件号",name = "PartNumber",
           type = "input-text", tips = "<span class='maroon'>*</span>请填写零件号",vaildType = "required,maxlength:32",inputContent="",functionName="onkeyup",functionStr="value=value.replace(/[^\\d]/g,'')"},       
       new FormLineConfig(){desc = "零件名称",name = "PartName",
            type = "input-text", tips = "<span class='maroon'>*</span> 请填写零件具体名称",vaildType = "required,maxlength:32",inputContent="",functionStr=""} ,
       new FormLineConfig(){desc = "零件价格",name = "Price",
            type = "input-text", tips = "<span class='maroon'>*</span> 备注：此价格为建议零售价，仅包含零件本身的材料费用，不包括维修工时费等。",vaildType = "required",inputContent="",functionName="onkeyup",functionStr=""} ,
       new FormLineConfig(){desc = "零件图像",name = "PartAvata",
           type = "single-image", tips = "建议尺寸：88像素 * 88像素",vaildType = ""},
   };
 ViewBag.formsecondlines = new FormLineConfig[]{
       new FormLineConfig(){desc = "",name = "PartId",
            type = "input-hidden", tips = "",vaildType = "",inputContent = "",inputValue=""},
       new FormLineConfig(){desc = "",name = "OpenId",
            type = "input-hidden", tips = "",vaildType = "",inputContent = "",inputValue=""},
       new FormLineConfig(){desc = "",name = "WeixinPlatId",
            type = "input-hidden", tips = "",vaildType = "",inputContent = "",inputValue= Request.QueryString["plat"]}
   };

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 31 "..\..\Views\Part\EditPartInfo.cshtml"
Write(Html.Partial("_FormResource"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\Part\EditPartInfo.cshtml"
Write(Html.Partial("_KindEditorResource"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Views\Part\EditPartInfo.cshtml"
Write(Html.Partial("_DateTimePickerResource", new ViewDataDictionary() { { "className", "form_datetime" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"span12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Part\EditPartInfo.cshtml"
               Write(Html.Partial("GoBackButton"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"span10\"");

WriteLiteral(">\r\n                            <h3>\r\n                                <i");

WriteLiteral(" class=\"icon-edit\"");

WriteLiteral("></i>");

            
            #line 43 "..\..\Views\Part\EditPartInfo.cshtml"
                                                    Write(formTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </h3>\r\n                        </div>\r\n            " +
"            <div");

WriteLiteral(" class=\"span2\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"box-content\"");

WriteLiteral(">\r\n                        <form");

WriteLiteral(" action=\"\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" class=\"form-horizontal form-validate\"");

WriteLiteral(" id=\"form1\"");

WriteLiteral(" name=\"form1\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 51 "..\..\Views\Part\EditPartInfo.cshtml"
                        Write(new CreateForm().CreateFormBody(ViewBag.formlines));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                            ");

            
            #line 53 "..\..\Views\Part\EditPartInfo.cshtml"
                        Write(new CreateForm().CreateFormBody(ViewBag.formsecondlines, false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 54 "..\..\Views\Part\EditPartInfo.cshtml"
                       Write(Html.Partial("CreateFormFoot"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </form>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var id = jQuery.query.get(\"id\");\r\n    var opts = {\r\n        primaryKeyId: " +
"id,\r\n        getFormDataUrl: \'");

            
            #line 66 "..\..\Views\Part\EditPartInfo.cshtml"
                    Write(Url.Action("GetPartInformationEntityById", "Part"));

            
            #line default
            #line hidden
WriteLiteral("?id=\' + id,\r\n        postFormDataUrl: \'");

            
            #line 67 "..\..\Views\Part\EditPartInfo.cshtml"
                     Write(Url.Action("InsertOrUpdatePartInformationEntity", "Part"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        returnUrl: \'");

            
            #line 68 "..\..\Views\Part\EditPartInfo.cshtml"
               Write(Url.Action("PartInformation", "Part"));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Part\EditPartInfo.cshtml"
                                                     Write(Html.Raw(@ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        validateOpts: {\r\n            rules: {\r\n");

WriteLiteral("                ");

            
            #line 71 "..\..\Views\Part\EditPartInfo.cshtml"
            Write(new CreateForm().CreateFormValid(ViewBag.formlines));

            
            #line default
            #line hidden
WriteLiteral(@"
            }
        }
    };

    formClass.extFunction.validateFun = function () {
        if (imgEntity.ResourceUrl === undefined || imgEntity.ResourceUrl === """") {
            imgEntity.showError(false, ""请上传零件图片"");
            return false;
        }
        else {
            imgEntity.showError(true);
            return true;
        }        
    };

    formClass.extFunction.serializeFormFun = function (json) {
        var jsondata = { ""json"": json, ""plat"": jQuery.query.get(""plat"") };
        return jsondata;
    };
    $(function () {
        formClass.init(opts);
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
