#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/WorkOrderOut/WorkOrderOut.cshtml")]
    public partial class _Views_WorkOrderOut_WorkOrderOut_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_WorkOrderOut_WorkOrderOut_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
  
    ViewBag.Title = "WorkOrderOut";
    ViewBag.subTitle = "工单管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var platid = Request["plat"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 165), Tuple.Create("\"", 230)
            
            #line 7 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 171), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery.form.js?v=")
            
            #line default
            #line hidden
, 171), false)
            
            #line 7 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 214), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 214), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 273), Tuple.Create("\"", 340)
            
            #line 8 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 279), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ZeroClipboard.js?v=")
            
            #line default
            #line hidden
, 279), false)
            
            #line 8 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 324), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 324), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
Write(Html.Partial("_ListResource"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 641), Tuple.Create("\"", 740)
            
            #line 14 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 648), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/datetimepicker/bootstrap-datetimepicker.min.css?v=")
            
            #line default
            #line hidden
, 648), false)
            
            #line 14 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
         , Tuple.Create(Tuple.Create("", 724), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 724), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 786), Tuple.Create("\"", 883)
            
            #line 15 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 792), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/datetimepicker/bootstrap-datetimepicker.min.js?v=")
            
            #line default
            #line hidden
, 792), false)
            
            #line 15 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
         , Tuple.Create(Tuple.Create("", 867), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 867), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 926), Tuple.Create("\"", 1033)
            
            #line 16 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 932), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js?v=")
            
            #line default
            #line hidden
, 932), false)
            
            #line 16 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
                  , Tuple.Create(Tuple.Create("", 1017), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 1017), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" class=\"maincontentinner1\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" id=\"Div12\"");

WriteLiteral(" class=\"dataTables_wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"dyntable_length\"");

WriteLiteral(" class=\"dataTables_length\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n\r\n                <label>\r\n                    ");

WriteLiteral("\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2060), Tuple.Create("\"", 2144)
            
            #line 38 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 2067), Tuple.Create<System.Object, System.Int32>(Url.Action("AddInfo", "HotLine")
            
            #line default
            #line hidden
, 2067), false)
            
            #line 38 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 2100), Tuple.Create<System.Object, System.Int32>(Html.Raw(@ViewBag.oQueryString)
            
            #line default
            #line hidden
, 2100), false)
, Tuple.Create(Tuple.Create("", 2132), Tuple.Create("&type=repair", 2132), true)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">\r\n                        修改\r\n                    </a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2248), Tuple.Create("\"", 2332)
            
            #line 41 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 2255), Tuple.Create<System.Object, System.Int32>(Url.Action("AddInfo", "HotLine")
            
            #line default
            #line hidden
, 2255), false)
            
            #line 41 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
, Tuple.Create(Tuple.Create("", 2288), Tuple.Create<System.Object, System.Int32>(Html.Raw(@ViewBag.oQueryString)
            
            #line default
            #line hidden
, 2288), false)
, Tuple.Create(Tuple.Create("", 2320), Tuple.Create("&type=change", 2320), true)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">\r\n                        转为工单\r\n                    </a>\r\n                    <a" +
"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnBatchExport\"");

WriteLiteral(">\r\n                        导出\r\n                    </a>\r\n                </label>" +
"\r\n            </div>\r\n            <span");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"TicketNumber\"");

WriteLiteral(" id=\"TicketNumber\"");

WriteLiteral(" class=\"search\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"color: gray\"");

WriteLiteral(" placeholder=\"请输入维修项名称\"");

WriteLiteral(" onkeyup=\"value=value.replace(/[\\\']+/, \'\') \"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"RepairQueryNum\"");

WriteLiteral(" id=\"RepairQueryNum\"");

WriteLiteral(" class=\"search\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"color: gray\"");

WriteLiteral(" placeholder=\"请输入维修项查询号\"");

WriteLiteral(" onkeyup=\"value=value.replace(/[\\\']+/, \'\') \"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnselect\"");

WriteLiteral(">查询</button>\r\n            </span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_filter\"");

WriteLiteral(" id=\"dyntable_filter\"");

WriteLiteral(">\r\n        </div>\r\n        <table");

WriteLiteral(" id=\"Table1\"");

WriteLiteral(" class=\"table table-bordered responsive dataTable\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th>
                        1
                    </th>
                    <th>
                        2
                    </th>
                    <th>
                        3
                    </th>
                    <th>
                        4
                    </th>
                    <th>
                        5
                    </th>
                    <th>
                        6
                    </th>
                    <th>
                        7
                    </th>
                </tr>
            </thead>
            <tbody");

WriteLiteral(" id=\"tableBody\"");

WriteLiteral("></tbody>\r\n        </table>\r\n        <div");

WriteLiteral(" class=\"dataTables_info\"");

WriteLiteral(" id=\"Div25\"");

WriteLiteral(">\r\n            &nbsp;\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_paginate paging_bootstrap pagination\"");

WriteLiteral(" id=\"Div26\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" id=\"tableFoot\"");

WriteLiteral("></ul>\r\n        </div>\r\n    </div>\r\n    <br>\r\n    <br>\r\n</div>\r\n<!--列表模板-->\r\n\r\n<s" +
"cript");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(" id=\"replylist\"");

WriteLiteral(">\r\n\r\n    ");

WriteLiteral("\r\n    <div id=\"dateail_${RepairId}\"></div>\r\n\r\n</script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\nvar plat = jQuery.query.get(\"plat\");\r\n    var opts = {\r\n        getListUrl: \'");

            
            #line 165 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
                Write(Url.Action("GetUnitInformationPageList", "Unit"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        footUrl: \'");

            
            #line 166 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
             Write(Url.Content("~/Content/tmpl/foot1.htm"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        tableBodyId: \"tableBody\",\r\n        tableFootId: \"tableFoot\",\r\n       " +
" replyListId: \"replylist\",\r\n        pageSize: 15,\r\n        deleteUrl: \'");

            
            #line 171 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
               Write(Url.Action("DeleteUserListEntityById", "Unit"));

            
            #line default
            #line hidden
WriteLiteral(@"',
        itemId: ""item-id"",
        cssClass: "".btn-del-open"",
        plat: plat,
        checkBox: """"
    };

    $(function () {
        //初始化列表数据
        //listClass.init(opts);
        //初始化导入记录
        //init();
        //搜索
        $(""#btnBatchExport"").click(function () {
            var TicketNumber = $('#TicketNumber').val();
            //var txtCompany = $('#txtCompany').val();
            //var date = $(""#date"").val();
            ");

WriteLiteral("\r\n            location.href = \'");

            
            #line 189 "..\..\Views\WorkOrderOut\WorkOrderOut.cshtml"
                        Write(Url.Action("ExportHotLineInfoToExcel", "HotLine"));

            
            #line default
            #line hidden
WriteLiteral("?TicketNumber=\' + TicketNumber;\r\n            return false;\r\n        });\r\n    })\r\n" +
"\r\n\r\n    ");

WriteLiteral("\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
