#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Dealer/DealerInfo.cshtml")]
    public partial class _Views_Dealer_DealerInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Dealer_DealerInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Dealer\DealerInfo.cshtml"
  
    ViewBag.Title = "WeiPhotoList";
    ViewBag.subTitle = "授权经销商管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var platid = Request["plat"];
    //var Status = Qxun.UI.Background.App_Code.CreateForm.GetEnumNameByType(typeof(Qxun.App.Plugins.NemakCore.Public.Status), "Status");

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 306), Tuple.Create("\"", 371)
            
            #line 8 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 312), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery.form.js?v=")
            
            #line default
            #line hidden
, 312), false)
            
            #line 8 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 355), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 355), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 414), Tuple.Create("\"", 481)
            
            #line 9 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 420), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ZeroClipboard.js?v=")
            
            #line default
            #line hidden
, 420), false)
            
            #line 9 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 465), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 465), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" class=\"tag mg-bottom-20 clr\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"alert\"");

WriteLiteral(" style=\"width:700px\"");

WriteLiteral("><span");

WriteLiteral(" id=\"notice\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral("></span>&nbsp;&nbsp;&nbsp;&nbsp;<span");

WriteLiteral(" id=\"alert\"");

WriteLiteral(">你好，这是首次登陆,没有历史导入导出记录</span></div>\r\n</div>\r\n");

            
            #line 14 "..\..\Views\Dealer\DealerInfo.cshtml"
Write(Html.Partial("_ListResource"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 770), Tuple.Create("\"", 869)
            
            #line 15 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 777), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/datetimepicker/bootstrap-datetimepicker.min.css?v=")
            
            #line default
            #line hidden
, 777), false)
            
            #line 15 "..\..\Views\Dealer\DealerInfo.cshtml"
         , Tuple.Create(Tuple.Create("", 853), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 853), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 915), Tuple.Create("\"", 1012)
            
            #line 16 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 921), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/datetimepicker/bootstrap-datetimepicker.min.js?v=")
            
            #line default
            #line hidden
, 921), false)
            
            #line 16 "..\..\Views\Dealer\DealerInfo.cshtml"
         , Tuple.Create(Tuple.Create("", 996), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 996), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1055), Tuple.Create("\"", 1162)
            
            #line 17 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1061), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js?v=")
            
            #line default
            #line hidden
, 1061), false)
            
            #line 17 "..\..\Views\Dealer\DealerInfo.cshtml"
                  , Tuple.Create(Tuple.Create("", 1146), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 1146), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" class=\"maincontentinner1\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" id=\"Div12\"");

WriteLiteral(" class=\"dataTables_wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"dyntable_length\"");

WriteLiteral(" class=\"dataTables_length\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n\r\n                <label>\r\n                    \r\n                    <a");

WriteLiteral(" href=\"#importMember\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(">\r\n                        导入数据\r\n                    </a>\r\n                    <a" +
"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnBatchExport\"");

WriteLiteral(">\r\n                        批量导出\r\n                    </a>\r\n                    <a" +
"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"btnBatchExportERP\"");

WriteLiteral(">\r\n                        ERP导出\r\n                    </a>\r\n                </lab" +
"el>\r\n            </div>\r\n            <span");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">                   \r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"SiteName\"");

WriteLiteral(" id=\"SiteName\"");

WriteLiteral(" class=\"search\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"color: gray\"");

WriteLiteral(" placeholder=\"请输入站点名称\"");

WriteLiteral(" onkeyup=\"value=value.replace(/[\\\']+/, \'\') \"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"CompanyName\"");

WriteLiteral(" id=\"CompanyName\"");

WriteLiteral(" class=\"search\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"color: gray\"");

WriteLiteral(" placeholder=\"请输入站点公司名称\"");

WriteLiteral(" onkeyup=\"value=value.replace(/[\\\']+/, \'\') \"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnselect\"");

WriteLiteral(">查询</button>\r\n\r\n</span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_filter\"");

WriteLiteral(" id=\"dyntable_filter\"");

WriteLiteral(">\r\n        </div>\r\n        <table");

WriteLiteral(" id=\"Table1\"");

WriteLiteral(" class=\"table table-bordered responsive dataTable\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th>\r\n         " +
"               BPCode\r\n                    </th>\r\n                    ");

WriteLiteral(@"
                    <th>
                        站点名称
                    </th>
                    <th>
                       站点负责人
                    </th>
                    <th>
                        联系电话
                    </th>
                    <th>
                        站点地址
                    </th>
                    <th>
                        成立日期
                    </th>
                    <th>
                        公司名称
                    </th>
                    <th>
                        类型
                    </th>
                    <th>
                        等级
                    </th>
                    <th>
                        区域经理
                    </th>
                </tr>
            </thead>
            <tbody");

WriteLiteral(" id=\"tableBody\"");

WriteLiteral("></tbody>\r\n        </table>\r\n        <div");

WriteLiteral(" class=\"dataTables_info\"");

WriteLiteral(" id=\"Div25\"");

WriteLiteral(">\r\n            &nbsp;\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_paginate paging_bootstrap pagination\"");

WriteLiteral(" id=\"Div26\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" id=\"tableFoot\"");

WriteLiteral("></ul>\r\n        </div>\r\n    </div>\r\n    <br>\r\n    <br>\r\n</div>\r\n<!--列表模板-->\r\n\r\n<s" +
"cript");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(" id=\"replylist\"");

WriteLiteral(">\r\n\r\n    <tr class=\"gradeX odd\" id=\"tr${DealerId}\">\r\n        <td class=\" \">\r\n    " +
"        ${BPCode}\r\n        </td>\r\n        ");

WriteLiteral(@"
        <td class="" "">
            ${SiteName}
        </td>
        <td class="" "">
            ${SiteManager}
        </td>
        <td class="" "">
            ${Tel}
        </td>
        <td class="" "">
            ${SiteAddress}
        </td>
        <td class="" "">
            ${formatDate(EstablishmentTime)}
        </td>
        <td class="" "">
            ${CompanyName}
        </td>
        <td class="" "">
            ${SiteType}
        </td>
        <td class="" "">
            ${SiteGrade}
        </td>
        <td class="" "">
            ${LocalManager}
        </td>
        </tr>
        <div id=""dateail_${DealerId}""></div>

    </script>
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var plat = jQuery.query.get(\"plat\");\r\n    var opts = {\r\n        getListUrl" +
": \'");

            
            #line 143 "..\..\Views\Dealer\DealerInfo.cshtml"
                Write(Url.Action("GetDealerPageList", "Dealer"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        footUrl: \'");

            
            #line 144 "..\..\Views\Dealer\DealerInfo.cshtml"
             Write(Url.Content("~/Content/tmpl/foot1.htm"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        tableBodyId: \"tableBody\",\r\n        tableFootId: \"tableFoot\",\r\n       " +
" replyListId: \"replylist\",\r\n        pageSize: 15,\r\n        ");

WriteLiteral(@"
        itemId: ""item-id"",
        cssClass: "".btn-del-open"",
        plat: plat,
        checkBox: """"
    };



    $(function () {
        //初始化列表数据
        listClass.init(opts);
        //初始化导入记录
        init();
        //搜索
        $(""#btnselect"").click(function () {
            var entity = new Object();
            entity.SiteName = $(""#SiteName"").val();
            entity.CompanyName = $(""#CompanyName"").val();
            var searchJson = JSON.stringify(entity);
            opts.getListUrl = '");

            
            #line 169 "..\..\Views\Dealer\DealerInfo.cshtml"
                          Write(Url.Action("GetDealerPageList", "Dealer"));

            
            #line default
            #line hidden
WriteLiteral(@"?searchJson=' + searchJson;
            listClass.init(opts);
        });

        $(""#btnBatchExport"").click(function () {
            var SiteName = $('#SiteName').val();
            var CompanyName = $('#CompanyName').val();
            location.href = '");

            
            #line 176 "..\..\Views\Dealer\DealerInfo.cshtml"
                        Write(Url.Action("ExportDealerinfoToExcel", "Dealer"));

            
            #line default
            #line hidden
WriteLiteral(@"?SiteName=' + SiteName + '&CompanyName=' + CompanyName;
            return false;
        });

        $(""#btnBatchExportERP"").click(function () {
            var SiteName = $('#SiteName').val();
            var CompanyName = $('#CompanyName').val();
            location.href = '");

            
            #line 183 "..\..\Views\Dealer\DealerInfo.cshtml"
                        Write(Url.Action("ExportDealerinfoToExcelERP", "Dealer"));

            
            #line default
            #line hidden
WriteLiteral("?SiteName=\' + SiteName + \'&CompanyName=\' + CompanyName;\r\n            return false" +
";\r\n        });\r\n\r\n    })\r\n\r\n    function init() {\r\n        $.post(\"");

            
            #line 190 "..\..\Views\Dealer\DealerInfo.cshtml"
           Write(Url.Action("Record", "Dealer"));

            
            #line default
            #line hidden
            
            #line 190 "..\..\Views\Dealer\DealerInfo.cshtml"
                                          Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@""", {}, function (data) {
            //  if (data.IsSuccess) {
            //alert(""注册成功"");
            if (data.AllUploadRecord != null) {
                var success = data.SuccessRecord;
                var fail = data.FailRecord;
                var time = formatDate(data.UploadTime).split(""."")[0];
                var all = data.AllUploadRecord;
                var a = document.getElementById(""alert"");
                var b = document.getElementById(""notice"");
                a.innerHTML = ""上次历史上传成功"" + success + ""条，失败"" + fail + ""条，总共上传"" + all + ""条，上传时间:"" + time + "",现有总数据为：");

            
            #line 200 "..\..\Views\Dealer\DealerInfo.cshtml"
                                                                                                             Write(ViewBag.TotalCount);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                a.innerHTML = \"上次上传时间为：\" + time + \"，总共上传\" + all + \"条数据，其中成功\" " +
"+ success + \"条，失败\" + fail + \"条。\"\r\n                b.innerHTML = \"现有总数据条数为：");

            
            #line 202 "..\..\Views\Dealer\DealerInfo.cshtml"
                                   Write(ViewBag.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(" 条。         \"\r\n            }\r\n        });\r\n    }\r\n\r\n\r\n</script>\r\n\r\n\r\n<!--数据加载的提示-" +
"->\r\n\r\n<div");

WriteLiteral(" id=\"load\"");

WriteLiteral(" class=\"tipsClass\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"importMember\"");

WriteLiteral(" class=\"modal hide fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral("\r\n     aria-hidden=\"false\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <form");

WriteLiteral(" id=\"Form1\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                        ×\r\n                    </button>\r\n                    " +
"<h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">\r\n                        批量导入授权经销商信息\r\n                    </h4>\r\n              " +
"  </div>\r\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\r\n                        文件大小不要超过1M，数据量小于5000条！\r\n                    </div>\r\n  " +
"                  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8465), Tuple.Create("\"", 8517)
            
            #line 231 "..\..\Views\Dealer\DealerInfo.cshtml"
, Tuple.Create(Tuple.Create("", 8472), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/tmpl/DealerList.csv")
            
            #line default
            #line hidden
, 8472), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"green\"");

WriteLiteral(">\r\n                        下载内容格式模板文件DealerList.csv\r\n                    </a>\r\n  " +
"                  <div");

WriteLiteral(" style=\"padding-bottom: 14px;font: 16px verdana;\"");

WriteLiteral(">\r\n                        上传文件：\r\n                        <span");

WriteLiteral(" style=\"vertical-align: middle;margin-right: 14px;margin-left: 12px;font-size: 16" +
"px;\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"file\"");

WriteLiteral(" name=\"file1\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" style=\" font-size: 16px; /* vertical-align: middle; */ padding-top: 3px; line-he" +
"ight: 20px; height: 28px;\"");

WriteLiteral(" />\r\n                        </span>\r\n                    </div>\r\n\r\n             " +
"       <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"weiXinUserId\"");

WriteLiteral(" />\r\n                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"groupID\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                        取消\r\n                    </button>\r\n                   " +
" <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary uploadbtn\"");

WriteLiteral(" ");

WriteLiteral(">\r\n                        提交\r\n                    </button>\r\n                </d" +
"iv>\r\n            </form>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        $("".uploadbtn"").click(function () {
            var fileName = $(""#file"").val();
            var fileLenght = fileName.length;
            var fileEnd = fileName.substring(fileLenght - 4, fileLenght);
            if (fileEnd == "".csv"") {
                jQuery(""#Form1"").ajaxSubmit({
                    url: '");

            
            #line 264 "..\..\Views\Dealer\DealerInfo.cshtml"
                     Write(Url.Action("ImportDealerListByFile", "Dealer"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    // data: { vipType: vipType },
                    success: function (responseTexts) {
                        //  var responseText = JSON.parse(responseTexts);
                        if (responseTexts.IsSuccess) {
                            alert(""程序正在后台上传,请稍后刷新查看上传记录!"");
                            $('#importMember').modal('hide');
                        }

                        else {
                            $('#importMember').modal('hide');
                            location.reload();
                        }
                    },
                    complete: function (xhr, ts) { xhr = null },
                    error: function (content) { alert(""文件格式错误！""); }
                })
            } else {
                alert(""请上传.cvs格式的文档"")
            }
        })
    })
</script>");

        }
    }
}
#pragma warning restore 1591
