#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MessageBoard/MessageBoardList.cshtml")]
    public partial class _Views_MessageBoard_MessageBoardList_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MessageBoard_MessageBoardList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
  
    ViewBag.Title = "MessageBoardList";
    ViewBag.subTitle = "留言管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var platid = Request["plat"];
    //var Status = Qxun.UI.Background.App_Code.CreateForm.GetEnumNameByType(typeof(Qxun.App.Plugins.NemakCore.Public.Status), "Status");

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 307), Tuple.Create("\"", 372)
            
            #line 8 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 313), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery.form.js?v=")
            
            #line default
            #line hidden
, 313), false)
            
            #line 8 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 356), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 356), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 415), Tuple.Create("\"", 482)
            
            #line 9 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 421), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ZeroClipboard.js?v=")
            
            #line default
            #line hidden
, 421), false)
            
            #line 9 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 466), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 466), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n");

            
            #line 11 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
Write(Html.Partial("_ListResource"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 557), Tuple.Create("\"", 644)
            
            #line 12 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 564), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/daterangepicker/daterangepicker.css?v=")
            
            #line default
            #line hidden
, 564), false)
            
            #line 12 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 628), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 628), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 690), Tuple.Create("\"", 761)
            
            #line 13 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 696), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery1.9-migrate.js?v=")
            
            #line default
            #line hidden
, 696), false)
            
            #line 13 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 745), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 745), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 804), Tuple.Create("\"", 889)
            
            #line 14 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 810), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/daterangepicker/daterangepicker.js?v=")
            
            #line default
            #line hidden
, 810), false)
            
            #line 14 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 873), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 873), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 932), Tuple.Create("\"", 1012)
            
            #line 15 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 938), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/daterangepicker/moment.min.js?v=")
            
            #line default
            #line hidden
, 938), false)
            
            #line 15 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 996), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 996), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1055), Tuple.Create("\"", 1122)
            
            #line 16 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 1061), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ZeroClipboard.js?v=")
            
            #line default
            #line hidden
, 1061), false)
            
            #line 16 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
, Tuple.Create(Tuple.Create("", 1106), Tuple.Create<System.Object, System.Int32>(ViewBag.Version
            
            #line default
            #line hidden
, 1106), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<div");

WriteLiteral(" class=\"maincontentinner1\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"Div12\"");

WriteLiteral(" class=\"dataTables_wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"dyntable_length\"");

WriteLiteral(" class=\"dataTables_length\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
             if (ViewBag.CopyUrl != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" id=\"btnCopyTo\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" style=\"margin-left: 5px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
               Write(Html.Raw("复制留言链接"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n");

            
            #line 25 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"controls input-prepend\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"add-on1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-calendar\"");

WriteLiteral("></i></span>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"date\"");

WriteLiteral(" id=\"MessageDate\"");

WriteLiteral(" class=\"input-large daterangepick valid\"");

WriteLiteral("\r\n                           readonly=\"readonly\"");

WriteLiteral(" title=\"订单的起始和结束时间\"");

WriteLiteral(">\r\n                </div>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"MessageContent\"");

WriteLiteral(" id=\"MessageContent\"");

WriteLiteral(" class=\"search\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"color: gray\"");

WriteLiteral(" placeholder=\"请输入留言内容\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn m-bottom-10\"");

WriteLiteral(" id=\"btnselect\"");

WriteLiteral(">查询</button>\r\n\r\n            </span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_filter\"");

WriteLiteral(" id=\"dyntable_filter\"");

WriteLiteral(">\r\n        </div>\r\n        <table");

WriteLiteral(" id=\"Table1\"");

WriteLiteral(" class=\"table table-bordered responsive dataTable\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th>
                        客户姓名
                    </th>
                    <th>
                        手机号
                    </th>
                    <th>
                        留言标题
                    </th>
                    <th>
                        留言内容
                    </th>
                    <th>
                        留言时间
                    </th>
                    <th>
                        操作
                    </th>
                </tr>
            </thead>
            <tbody");

WriteLiteral(" id=\"tableBody\"");

WriteLiteral("></tbody>\r\n        </table>\r\n        <div");

WriteLiteral(" class=\"dataTables_info\"");

WriteLiteral(" id=\"Div25\"");

WriteLiteral(">\r\n            &nbsp;\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_paginate paging_bootstrap pagination\"");

WriteLiteral(" id=\"Div26\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" id=\"tableFoot\"");

WriteLiteral("></ul>\r\n        </div>\r\n    </div>\r\n    <br>\r\n    <br>\r\n</div>\r\n<!--列表模板-->\r\n\r\n<s" +
"cript");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(" id=\"replylist\"");

WriteLiteral(@">

    <tr class=""gradeX odd"" id=""tr${Id}"">
        <td class="" "">
            ${CustomerName}
        </td>
        <td class="" "">
            ${TelPhone}
        </td>
        <td class="" "">
            ${MessageTitle}
        </td>
        <td class="" "">
            ${MessageContent}
        </td>
        <td class="" "">
            ${formatDate(MessageDate)}
        </td>
        <td class="" "">
            <a href=""");

            
            #line 95 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                Write(Url.Action("MessageBoardInfo", "MessageBoard"));

            
            #line default
            #line hidden
            
            #line 95 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                                                               Write(Html.Raw(@ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("&id=${Id}\" class=\"handleIcon btn-hide-open\" title=\"查看\"></a>\r\n        </td>\r\n    <" +
"/tr>\r\n    <div id=\"dateail_${DealerId}\"></div>\r\n\r\n</script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var plat = jQuery.query.get(\"plat\");\r\n    var opts = {\r\n        getListUrl" +
": \'");

            
            #line 104 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                Write(Url.Action("GetMessageBoardEntities", "MessageBoard"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        footUrl: \'");

            
            #line 105 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
             Write(Url.Content("~/Content/tmpl/foot1.htm"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        tableBodyId: \"tableBody\",\r\n        tableFootId: \"tableFoot\",\r\n       " +
" replyListId: \"replylist\",\r\n        pageSize: 15,\r\n        ");

WriteLiteral(@"
        itemId: ""item-id"",
        cssClass: "".btn-del-open"",
        plat: plat,
        checkBox: """"
    };



    $(function () {
        //初始化列表数据
        listClass.init(opts);
        if ($(""#btnCopyTo"").length > 0) {
            ZeroClipboard.setMoviePath('");

            
            #line 123 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                                   Write(Url.Content("~/Scripts/ZeroClipboard.swf?v="));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                                                                                 Write(ViewBag.Version);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n            var clip = new ZeroClipboard.Client(); // 新建一个对象\r\n            cl" +
"ip.setHandCursor(true); // 设置鼠标为手型\r\n            clip.setText(\'");

            
            #line 126 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                     Write(ViewBag.CopyUrl);

            
            #line default
            #line hidden
WriteLiteral(@"'.replace(/&amp;/g, ""&"")); // 设置要复制的文本。
            clip.glue(""btnCopyTo""); // 和上一句位置不可调换
            clip.addEventListener(""complete"", function () {
                alert(""链接已成功复制到剪贴板，右键选择粘贴或按键盘快捷键“Ctrl+V“即可使用"");
            });
        }
        //搜索
        $(""#btnselect"").click(function () {
            var entity = new Object();
            var messageTime = $(""#MessageDate"").val();
            var messageContent = $.trim($(""#MessageContent"").val());
            opts.getListUrl = '");

            
            #line 137 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                          Write(Url.Action("GetMessageBoardEntities", "MessageBoard"));

            
            #line default
            #line hidden
WriteLiteral(@"?messageTime=' + messageTime + ""&messageContent="" + messageContent;
            listClass.init(opts);
        });
        //加载双日历
        jQuery('#MessageDate').daterangepicker({
            presetRanges: [
                { text: 'My Range', dateStart: '");

            
            #line 143 "..\..\Views\MessageBoard\MessageBoardList.cshtml"
                                           Write(DateTime.Now);

            
            #line default
            #line hidden
WriteLiteral("\', dateEnd: \'Today\' }\r\n            ],\r\n            format: \"YYYY-MM-DD\"\r\n        " +
"});\r\n    })\r\n</script>\r\n<!--数据加载的提示-->\r\n<div");

WriteLiteral(" id=\"load\"");

WriteLiteral(" class=\"tipsClass\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
