#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/MessageBoardMobile/MessageBoardInfo.cshtml")]
    public partial class _Mobile_Views_MessageBoardMobile_MessageBoardInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_MessageBoardMobile_MessageBoardInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
  
    var id = Request["id"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale" +
"=1.0, user-scalable=no\"");

WriteLiteral("\r\n          name=\"viewport\"");

WriteLiteral(">\r\n    <!-- #Mobile Devices Support -->\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-touch-fullscreen\"");

WriteLiteral(" content=\"YES\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"format-detection\"");

WriteLiteral(" content=\"telephone=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, " +
"user-scalable=no\"");

WriteLiteral(">\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 781), Tuple.Create("\"", 845)
            
            #line 17 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
, Tuple.Create(Tuple.Create("", 788), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 788), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 919), Tuple.Create("\"", 976)
            
            #line 18 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
, Tuple.Create(Tuple.Create("", 926), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 926), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1103), Tuple.Create("\"", 1150)
            
            #line 20 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1109), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 1109), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1197), Tuple.Create("\"", 1254)
            
            #line 21 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1203), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 1203), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1301), Tuple.Create("\"", 1346)
            
            #line 22 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1307), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 1307), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1393), Tuple.Create("\"", 1438)
            
            #line 23 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1399), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.tmpl.min.js")
            
            #line default
            #line hidden
, 1399), false)
);

WriteLiteral("></script>\r\n\r\n    <title>我的留言</title>\r\n</head>\r\n<body>\r\n    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            我的留言\r\n                        </a>\r\n              " +
"      </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n       " +
" <!-- end header nav-->\r\n    </header>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"basic-form\"");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                                <!-- Form with placeholder -->\r\n            " +
"                    <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"card-panel\"");

WriteLiteral(">\r\n                                        <h4");

WriteLiteral(" class=\"header2\"");

WriteLiteral(">留言详情</h4>\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <form");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" placeholder=\"John Doe\"");

WriteLiteral(" id=\"MessageTitle\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly>\r\n                                                        <label");

WriteLiteral(" for=\"first_name\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">标题</label>\r\n                                                    </div>\r\n        " +
"                                        </div>\r\n                                " +
"                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <textarea");

WriteLiteral(" placeholder=\"Oh WoW! Let me check this one too.\"");

WriteLiteral(" id=\"MessageContent\"");

WriteLiteral(" class=\"materialize-textarea\"");

WriteLiteral(" readonly></textarea>\r\n                                                        <l" +
"abel");

WriteLiteral(" for=\"email\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">留言内容</label>\r\n                                                    </div>\r\n      " +
"                                          </div>\r\n                              " +
"                  <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <textarea");

WriteLiteral(" placeholder=\"Oh WoW! Let me check this one too.\"");

WriteLiteral(" id=\"ReplyContent\"");

WriteLiteral(" class=\"materialize-textarea\"");

WriteLiteral(" readonly></textarea>\r\n                                                        <l" +
"abel");

WriteLiteral(" for=\"email\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">回复内容</label>\r\n                                                    </div>\r\n      " +
"                                          </div>\r\n                              " +
"                  <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                            <a");

WriteLiteral(" class=\"btn cyan waves-effect waves-light right\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4675), Tuple.Create("\"", 4772)
            
            #line 78 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
                                     , Tuple.Create(Tuple.Create("", 4682), Tuple.Create<System.Object, System.Int32>(Url.Action("MessageBoardMobileList", "MessageBoardMobile")
            
            #line default
            #line hidden
, 4682), false)
            
            #line 78 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
                                                                                                , Tuple.Create(Tuple.Create("", 4741), Tuple.Create<System.Object, System.Int32>(Html.Raw(ViewBag.oQueryString)
            
            #line default
            #line hidden
, 4741), false)
);

WriteLiteral(">\r\n                                                                返回\r\n          " +
"                                                      <i");

WriteLiteral(" class=\"mdi-content-send right\"");

WriteLiteral(@"></i>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <script>
        $(function () {
            $.post(""");

            
            #line 98 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
               Write(Url.Action("GetMessageBoardEntityById", "MessageBoardMobile"));

            
            #line default
            #line hidden
            
            #line 98 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
                                                                             Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\", { id: \'");

            
            #line 98 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardInfo.cshtml"
                                                                                                                      Write(id);

            
            #line default
            #line hidden
WriteLiteral(@"' }, function (data) {
                if (data != null) {
                    $(""#MessageTitle"").val(data.ExtInfo.MessageTitle);
                    $(""#MessageContent"").val(data.ExtInfo.MessageContent);
                    $(""#ReplyContent"").val(data.ExtInfo.ReplyContent);
                } else {
                    alert(data.ErrorMsg);
                }
            })
        });
    </script>

</body>
</html>");

        }
    }
}
#pragma warning restore 1591
