#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/MessageBoardMobile/MessageBoardEdit.cshtml")]
    public partial class _Mobile_Views_MessageBoardMobile_MessageBoardEdit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_MessageBoardMobile_MessageBoardEdit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale" +
"=1.0, user-scalable=no\"");

WriteLiteral("\r\n          name=\"viewport\"");

WriteLiteral(">\r\n    <!-- #Mobile Devices Support -->\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-touch-fullscreen\"");

WriteLiteral(" content=\"YES\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"format-detection\"");

WriteLiteral(" content=\"telephone=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, " +
"user-scalable=no\"");

WriteLiteral(">\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 745), Tuple.Create("\"", 809)
            
            #line 14 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
, Tuple.Create(Tuple.Create("", 752), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 752), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 883), Tuple.Create("\"", 940)
            
            #line 15 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
, Tuple.Create(Tuple.Create("", 890), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 890), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1067), Tuple.Create("\"", 1114)
            
            #line 17 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
, Tuple.Create(Tuple.Create("", 1073), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 1073), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1161), Tuple.Create("\"", 1218)
            
            #line 18 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
, Tuple.Create(Tuple.Create("", 1167), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 1167), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1265), Tuple.Create("\"", 1310)
            
            #line 19 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
, Tuple.Create(Tuple.Create("", 1271), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 1271), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1357), Tuple.Create("\"", 1402)
            
            #line 20 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
, Tuple.Create(Tuple.Create("", 1363), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.tmpl.min.js")
            
            #line default
            #line hidden
, 1363), false)
);

WriteLiteral("></script>\r\n\r\n    <title>我的留言</title>\r\n</head>\r\n<body>\r\n    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            我的留言\r\n                        </a>\r\n              " +
"      </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n       " +
" <!-- end header nav-->\r\n    </header>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"basic-form\"");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                                <!-- Form with placeholder -->\r\n            " +
"                    <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"card-panel\"");

WriteLiteral(">\r\n                                        <h4");

WriteLiteral(" class=\"header2\"");

WriteLiteral(">请填写信息</h4>\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <form");

WriteLiteral(" class=\"col s12\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" placeholder=\"John Doe\"");

WriteLiteral(" id=\"MessageTitle\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"first_name\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">标题</label>\r\n                                                    </div>\r\n        " +
"                                        </div>\r\n                                " +
"                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <textarea");

WriteLiteral(" placeholder=\"Oh WoW! Let me check this one too.\"");

WriteLiteral(" id=\"MessageContent\"");

WriteLiteral(" class=\"materialize-textarea\"");

WriteLiteral("></textarea>\r\n                                                        <label");

WriteLiteral(" for=\"email\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">内容</label>\r\n                                                    </div>\r\n        " +
"                                        </div>\r\n                                " +
"                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" placeholder=\"John Doe\"");

WriteLiteral(" id=\"CustomerName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"password\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">联系人</label>\r\n                                                    </div>\r\n       " +
"                                         </div>\r\n                               " +
"                 <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" placeholder=\"John Doe\"");

WriteLiteral(" id=\"TelPhone\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"message\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">联系电话</label>\r\n                                                    </div>\r\n      " +
"                                              <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"input-field col s12\"");

WriteLiteral(">\r\n                                                            <button");

WriteLiteral(" class=\"btn cyan waves-effect waves-light right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"submitBtn\"");

WriteLiteral(">\r\n                                                                提交\r\n          " +
"                                                      <i");

WriteLiteral(" class=\"mdi-content-send right\"");

WriteLiteral(@"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <script>
    $(function () {
        $(""#submitBtn"").click(function () {
            var json = {
                ""Id"": """",
                ""TelPhone"": $(""#TelPhone"").val(),
                ""CustomerName"": $(""#CustomerName"").val(),
                ""MessageContent"": $(""#MessageContent"").val(),
                ""MessageTitle"": $(""#MessageTitle"").val(),
                ""MessageDate"": """",
                ""MessageStatus"": """",
                ""OpenId"": """",
                ""WeixinPlatId"": """",
                ""ReplyContent"":""""
            }
            $.post(""");

            
            #line 112 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
               Write(Url.Action("InsertOrUpdateMessageBoardEntity", "MessageBoardMobile"));

            
            #line default
            #line hidden
            
            #line 112 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
                                                                                    Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\", { entity: json }, function (data) {\r\n                if (data != null) {\r\n    " +
"                location.href = \"");

            
            #line 114 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
                                Write(Url.Action("MessageBoardMobileList", "MessageBoardMobile"));

            
            #line default
            #line hidden
            
            #line 114 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardEdit.cshtml"
                                                                                           Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                } else {\r\n                    alert(data.ErrorMsg);\r\n        " +
"        }\r\n            })\r\n        })\r\n    })\r\n    </script>\r\n\r\n</body>\r\n</html>" +
"");

        }
    }
}
#pragma warning restore 1591
