#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mobile/Views/MessageBoardMobile/MessageBoardMobileList.cshtml")]
    public partial class _Mobile_Views_MessageBoardMobile_MessageBoardMobileList_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Mobile_Views_MessageBoardMobile_MessageBoardMobileList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
  
    var MessageStatus = Qxun.UI.Background.App_Code.CreateForm.GetEnumNameByType(typeof(Qxun.App.Plugins.CarrierWechat.Public.MessageStatus), "MessageStatus");

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale" +
"=1.0, user-scalable=no\"");

WriteLiteral("\r\n          name=\"viewport\"");

WriteLiteral(">\r\n    <!-- #Mobile Devices Support -->\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-touch-fullscreen\"");

WriteLiteral(" content=\"YES\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"format-detection\"");

WriteLiteral(" content=\"telephone=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, " +
"user-scalable=no\"");

WriteLiteral(">\r\n    <!--Import materialize.css-->\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 913), Tuple.Create("\"", 977)
            
            #line 17 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
, Tuple.Create(Tuple.Create("", 920), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/materialize.min.css")
            
            #line default
            #line hidden
, 920), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1051), Tuple.Create("\"", 1108)
            
            #line 18 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
, Tuple.Create(Tuple.Create("", 1058), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/materialize/css/main.min.css")
            
            #line default
            #line hidden
, 1058), false)
);

WriteLiteral(" media=\"screen,projection\"");

WriteLiteral(" />\r\n    <!--Let browser know website is optimized for mobile-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1235), Tuple.Create("\"", 1282)
            
            #line 20 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
, Tuple.Create(Tuple.Create("", 1241), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery-1.11.2.min.js")
            
            #line default
            #line hidden
, 1241), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1329), Tuple.Create("\"", 1386)
            
            #line 21 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
, Tuple.Create(Tuple.Create("", 1335), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/materialize/materialize.min.js")
            
            #line default
            #line hidden
, 1335), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1433), Tuple.Create("\"", 1478)
            
            #line 22 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
, Tuple.Create(Tuple.Create("", 1439), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.validate.js")
            
            #line default
            #line hidden
, 1439), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1525), Tuple.Create("\"", 1570)
            
            #line 23 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
, Tuple.Create(Tuple.Create("", 1531), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.tmpl.min.js")
            
            #line default
            #line hidden
, 1531), false)
);

WriteLiteral("></script>\r\n    \r\n    <title>我的留言</title>\r\n</head>\r\n<body>\r\n    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"page-topbar\"");

WriteLiteral(">\r\n        <!-- start header nav-->\r\n        <div");

WriteLiteral(" class=\"navbar-fixed\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"cyan\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"nav-wrapper\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" class=\"logo-wrapper\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#!\"");

WriteLiteral(" class=\"brand-logo darken-1\"");

WriteLiteral(" style=\"margin:0;padding:0;line-height: 56px;\"");

WriteLiteral(">\r\n                            我的留言\r\n                        </a>\r\n              " +
"      </h1>\r\n                </div>\r\n            </nav>\r\n        </div>\r\n       " +
" <!-- end header nav-->\r\n    </header>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><a");

WriteLiteral(" class=\"btn waves-effect waves-light blue\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2449), Tuple.Create("\"", 2540)
            
            #line 48 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
                        , Tuple.Create(Tuple.Create("", 2456), Tuple.Create<System.Object, System.Int32>(Url.Action("MessageBoardEdit", "MessageBoardMobile")
            
            #line default
            #line hidden
, 2456), false)
            
            #line 48 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
                                                                             , Tuple.Create(Tuple.Create("", 2509), Tuple.Create<System.Object, System.Int32>(Html.Raw(ViewBag.oQueryString)
            
            #line default
            #line hidden
, 2509), false)
);

WriteLiteral(" style=\"width:80%\"");

WriteLiteral(">我要留言</a></p>\r\n                        <div");

WriteLiteral(" id=\"work-collections\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                                <div");

WriteLiteral(" class=\"col s12 m12 l6\"");

WriteLiteral(">\r\n                                    <ul");

WriteLiteral(" id=\"issues-collection\"");

WriteLiteral(" class=\"collection\"");

WriteLiteral(">\r\n                                        <li");

WriteLiteral(" class=\"collection-item\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"collection-header\"");

WriteLiteral(@">我的留言</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(" id=\"MessageBoardListTmpl\"");

WriteLiteral(">\r\n        <li class=\"collection-item\">\r\n            <a href=\"");

            
            #line 69 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
                Write(Url.Action("MessageBoardInfo", "MessageBoardMobile"));

            
            #line default
            #line hidden
            
            #line 69 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
                                                                     Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral(@"&id=${Id}"">
                <div class=""row"">
                    <div class=""col s8"">
                        <p class=""collections-title"">提交时间:${MessageDate}</p>
                    </div>
                    <div class=""col s4"">
                        <p class=""collections-title"">");

            
            #line 75 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
                                                Write(MessageStatus);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n            </a>\r\n     " +
"   </li>\r\n    </script>\r\n    <script>\r\n    $(function () {\r\n        $.post(\"");

            
            #line 83 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
           Write(Url.Action("GetMessageBoardMobileEntities", "MessageBoardMobile"));

            
            #line default
            #line hidden
            
            #line 83 "..\..\Mobile\Views\MessageBoardMobile\MessageBoardMobileList.cshtml"
                                                                             Write(Html.Raw(ViewBag.oQueryString));

            
            #line default
            #line hidden
WriteLiteral("\", {page:1,pageSize:100}, function (data) {\r\n            if (data!=null) {\r\n     " +
"           $(\"#MessageBoardListTmpl\").tmpl(data.ContentEntity.Body).appendTo(\"#i" +
"ssues-collection\");\r\n            }\r\n        })\r\n    })\r\n    </script>\r\n\r\n</body>" +
"\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
